version: "3.9"
services:
  app: 
    build:
      context: .
      dockerfile: ./python/Dockerfile
    image: "name001/pymysql"
    container_name: pymysqlclient
    depends_on:
      - db
    networks:
      - app-net
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
  db:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    ports:
      - target: 3306
        published: 3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    networks:
      - app-net
    volumes:
      - db_data:/var/lib/mysql
networks:
  app-net:
    driver: bridge
volumes:
  db_data: